# Ceci est ma configuration, elle peux être utiliser comme exemple
# This is my configuration, It can be used as an example

# ---- Pour mettre les écrans à des positions spécifiques les uns par rapport au autres
# Set a specific position for each monitors
monitor DP-1 -> 0 0
monitor HDMI-A-1 -> 1920 0

# ---- Les applications qui se lance au démarage
# Application launched at the start of the compositor
autoStart quickshell
autoStart wpaperd
# autoStart kitty

# ---- Les raccourci clavier (j'utilise les code xkb_sym donc pour les nom des touches clavier utiliser celle du site ci_dessous normalement) 
# https://xkbcommon.org/doc/current/xkbcommon-keysyms_8h.html
# Shortcuts (use xkb_sym for keys's full name)

# - Exec command
key -> super_l q | command -> kitty
key -> super_l e | command -> pcmanfm 
key -> super_l r | command -> rofi -show drun -disable-history -show-icons -config ~/.config/rofi/app-launcher.rasi

# TODO: add screen capture (not work curently)
# Ajouter la capture d'écran (ne fonctionne pas actuellement)
key -> print | command -> hyprshot -m region -s 
key -> super_l print | command -> hyprshot -m region -s -z

key -> super_l s | command -> steam 
key -> super_l o | command -> obsidian
key -> super_l w | command -> librewolf 

key -> super_l n | command -> swaync-client -t -sw 

# - action du compositeur 
key -> super_l f | compositorAction -> fullscreen
key -> super_l m | compositorAction -> exit
key -> super_l c | compositorAction -> killFocused

