# Ceci est ma configuration, elle peux être utiliser comme exemple
# This is my configuration, It can be used as an example

# Pour mettre les écrans à des positions spécifiques les uns par rapport au autres
# Set a specific position for each monitors
monitor DP-1 -> 0 0
monitor HDMI-A-1 -> 1920 0

# Les applications qui se lance au démarage
# Application launched at the start of the compositor
autoStart quickshell
autoStart wpaperd
# autoStart kitty

